### PR TITLE
FormData iOS patch

### PR DESCRIPTION
**Pull request by brianswenson**
replaced FormData which is not supported in iOS my manually generating the POST string.

### CODE REVIEW

**Comment by faelys** [comment]
Thanks a lot for developing the principle and testing this, but there is a little problem: you should URI-encode the values (and maybe also the names too, just to be on the safe side) before merging it in the `data` variable.

For example, if I used a password with a character `&` in an extra field, without the escape it would be cut into garbage. Similarly, if the HMAC is base-64 encoded and happen to contain a `+`, it would be messed up on the way.

So I can't accept this pull request as it is now.

Do you prefer submitting a new pull request with the added calls to `encodeURIComponent`, or to you prefer that I commit it directly myself (crediting you, of course)?

**Comment by brianswenson** [comment]
I added the the encodeURIComponent, I think this pull request has that included now so no need for a new pull request.

**Comment by faelys** [comment]
I didn't know you could change the pull request, so indeed there is no need for a new one.

I wondering whether `payload` also needs to be escaped. I'm sure it can contain unsafe characters (e.g. newline when bundling CSV lines, which is how I use it myself), but I'm a bit lost on how many levels of escaping are needed.

So you might want to add it or not, depending on how you feel the issue. I will test it next week-end (with my Android) and fix it one way or the other if needed.

**Comment by brianswenson** [comment]
It certainly doesn't hurt to URIencode payload as well.  I didn't think it was needed because that is generated from health data with the exception of the bundle separator which I believe is already URIencoded.

**Comment by faelys** [comment]
As I said, it's hard to keep track of all the places where encoding and decoding happen. However, I think the payload and the bundle separator are both unencoded, because the default value of the bundle separator is unencoded, and there is the extra encoding step for the bundle separator when `config.html` is loaded. There is an extra decoding step in `webviewclosed` handler too, but it's also there for the HMAC key and for the URI endpoint, so maybe I'm just lucky to not have special character there.

Anyway, thanks a lot for the patch, I will test it thoroughly on Saturday and hopefully release an iOS-ready version on Sunday.

**Pull request merged**
